/* eslint-disable */
/* global WebImporter */

/**
 * Transformer for WKND website cleanup
 * Purpose: Remove non-content elements (header, footer, navigation, sign-in, analytics)
 * Applies to: wknd.site (all templates)
 * Generated: 2026-02-25
 *
 * SELECTORS EXTRACTED FROM:
 * - Captured DOM during migration workflow (migration-work/cleaned.html)
 * - Source page: https://wknd.site/us/en.html
 */

const TransformHook = {
  beforeTransform: 'beforeTransform',
  afterTransform: 'afterTransform',
};

export default function transform(hookName, element, payload) {
  if (hookName === TransformHook.beforeTransform) {
    // Remove header experience fragment
    // EXTRACTED: Found <header class="experiencefragment cmp-experiencefragment--header">
    WebImporter.DOMUtils.remove(element, [
      'header.cmp-experiencefragment--header',
      '.experiencefragment.cmp-experiencefragment--header',
    ]);

    // Remove footer experience fragment
    // EXTRACTED: Found <footer class="experiencefragment cmp-experiencefragment--footer">
    WebImporter.DOMUtils.remove(element, [
      'footer.cmp-experiencefragment--footer',
      '.experiencefragment.cmp-experiencefragment--footer',
    ]);

    // Remove sign-in buttons
    // EXTRACTED: Found <div class="wknd-sign-in-buttons">
    WebImporter.DOMUtils.remove(element, [
      '.wknd-sign-in-buttons',
      '.sign-in-buttons',
    ]);

    // Remove language navigation
    // EXTRACTED: Found <div class="languagenavigation cmp-languagenavigation--default">
    WebImporter.DOMUtils.remove(element, [
      '.cmp-languagenavigation',
      '.languagenavigation',
    ]);

    // Remove carousel navigation controls (prev/next buttons, indicators)
    // These are generated by the source CMS, not authored content
    // EXTRACTED: Found <div class="cmp-carousel__actions"> and <ol class="cmp-carousel__indicators">
    WebImporter.DOMUtils.remove(element, [
      '.cmp-carousel__actions',
      '.cmp-carousel__indicators',
    ]);
  }

  if (hookName === TransformHook.afterTransform) {
    // Remove standard non-content HTML elements
    WebImporter.DOMUtils.remove(element, [
      'noscript',
      'iframe',
      'link',
    ]);
  }
}
